config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  resources :sessions, only: %i[new create destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  # get 'sessions/new'
  get 'users/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  resources :posts, only: %i[new create index]
  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, presence: true
  validates :comment, presence: true

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  before_create :create_remember_token
  has_many :posts

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :signed_in_user, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = 'Successfully posted!'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  def signed_in_user
    redirect_to signin_url unless signed_in?
  end

  private

  def post_params
    params.require(:post).permit(:title, :comment, :user_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    redirect_to root_url if signed_in?
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      flash[:success] = 'Thank you for signing in!'
      sign_in @user
      remember @user
      redirect_to posts_path
    else
      # Create an error message.
      flash[:error] = 'Can not verify your email of password'
      render 'new'
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Your account was created successfully. Please sign in to post.'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find(user_id)
      if user&.authenticate(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def signed_in?
    !current_user.nil?
  end

  # Remembers given user
  def remember(user)
    user.remember_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets given user
  def forget(_user)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Members only club house
  </small>
  <nav>
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Members Only Club", root_path, id: "logo", class: "align-middle"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Posts", posts_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Sign out", signout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members Only</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container" id="posts">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="float-right">
  <% if signed_in? %>
  <%= link_to "(#{current_user.name}) Sign out", signout_path, method: "delete" %>
  <% else %>
    <%= link_to 'Sign in', signin_path %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  <h3>Members Only Posts</h3>
  <% @posts.each do |post| %>

  <div class="card bg-info text-white">
    <div class="card-body">
      <% if signed_in? %>
        <p class="float-right">
          Posted by:
          <%= post.user.name %>
        </p>
      <% end %>
      <h4 class="float-left card-title"><%=post.title %></h4>
      <p class="clear card-text"><%= post.comment %></p>
    </div>
  </div>
  <br>
  <% end %>

  <% if signed_in? %>
    <%= link_to "Create a Post", new_post_path %>
  <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <h1 class="text-center">New Post</h1>

<%= form_for @post do |f| %>


  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :comment %>
  <%= f.text_area :comment, class: 'form-control' %>


  <%= f.submit "Create Post", class: "btn btn-large btn-primary form-control mt-1" %>

<% end %>

  </div>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Member's Club</h1>

  <h2 class="text-center">
    This is the home page for the Members Only Club of Microverse</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%#= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary form-control mt-1" %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
   <div class="col-md-6 col-md-offset-3">
       <%= render 'form'%>
   </div>
</div>